_posts/2020-11-05-curso-avanzado-de-sonarqube-en-espanol-y-en-vivo.md

Update - Nuevas fechas

---

_posts/2018-04-18-iso-25000.md

Contact form y enlance a la pagina de contacto

Update article ISO 25000

---

sonarsource.html

- Links updated
- Img alt updated
- Bottom banner (Link a Formación)

SonarSource

---

_posts/2021-02-08-traceabilityx-para-jira-nueva-version-3-6.md

Blog: New release TraceabilityX 3.6 - Update

---

_includes/nav.html

Link de Migración a Cloud en una nueva pagina

Migración Cloud: Link pagina externa en nueva pagina

---

sonarsource.html

Link a las paginas Developer, Enterprise, Data Center Edition Licence Request

Sonarsource (ES): Link a Developer, Enterprise, Data Center Edition

---

_includes/nav-en.html
en/licencias-atlassian.html
migracion-atlassian-cloud.html

Migración Atlassian Cloud ES - Corrección texto

---

curso-jira-confluence-cloud-usuarios.html
cursos-lista-espera.html

- Curso Jira y Confluence: Se ha añadido la posibilidad de suscribirse a la lista de espera
- Nueva página para registrarse en la lista de espera

Cursos: Lista de espera

---

_posts/2023-06-23-novedades-sonarqube-10-1.md

Correcciones del post novedades SonarQube 10.1

correccionjava20

---

_posts/2020-10-27-que-es-confluence-y-a-que-aporta-al-trabajo-remoto.md
_posts/2021-10-18-que-es-sonarqube-ediciones-y-precios.md
_posts/2022-07-21-sonarcloud-vs-sonarqube.md
_posts/2022-07-26-jql-la-forma-de-buscar-en-jira.md
_posts/2023-02-02-confluencecloud-sonarqube-connector-1.20_spanish.md
bitbucket.html
calidad-de-procesos.html
curso-sonarqube-administradores.html
en/sonarqube-developer-edition.html
en/sonarqube-enterprise-edition.html
excentia-admin-tools.html
servicios-atlassian-cloud.html
servicios-cloud-atlassian.html

Actualización de meta descripciones detectadas como cortas.

Correccionerrores

---

_posts/2010-09-09-las-pruebas-de-software-que-es-testear.html
_posts/2012-03-30-la-deuda-tecnica-y-el-metodo-sqale.html
_posts/2016-02-11-la-velocidad-de-una-caravana-en-el.html
_posts/2017-05-15-openexpo-the-future-is-open.md
_posts/2017-09-29-novedades-gestion-de-procesos.md
_posts/2017-12-1-resumen-SonarSource-City-Tour.md
_posts/2018-01-24-Transformacion-Digital-P1.md
_posts/2018-04-18-iso-25000.md
_posts/2019-05-07-top-vendor.md
atlassian.html
dcs-2018.html
en/sonarqube-connector-jira.html
formacion-empresas.html

Corrección de meta descripciones largas.

Metaslargas

---

_includes/blog-grid.html
_includes/blog-top-grid.html
_layouts/blog_en.html

- Revisar email BCasanovas
- Volver al blog anterior de solo noticias en ESP

Modificaciones blog ENG

---

curso-sonarqube-pack-maestria.html
curso-sonarqube-usuarios.html
en/sonarqube-connector-confluence.html
sonarqube-connector-confluence.html

- Añadir nuevo video Confluence
- Actualizar fechas Cursos Sonar

Actualización video y cursos Sonar

---

_posts/2024-04-28-evento-atlassian-valencia-team-24.md

Actualización de la agenda y url en el post

Actualización agenda Team-24 VLC

---

formacion.html
webinar-mejores-practicas-reducir-costes-software.html

- Añadido formulario en página de webinar
- Actualizado el boton para en formacion.html para que vaya al formulario

Actualización de formularios

---

_posts/2021-10-18-que-es-sonarqube-ediciones-y-precios.md
_posts/2021-12-15-que-es-sonarlint-y-como-mejora-calidad-codigo.md
evento-15-aniversario-excentia.html
sonarcloud.html
sonarlint.html
sonarqube.html
webinar-mejores-practicas-reducir-costes-software.html

Actualizar video y enlaces de webinar
Actualizar landing evento

Actualizaciones de página

---

evento-15-aniversario-excentia.html
webinar-mejores-practicas-reducir-costes-software.html

- Actualizar formulario evento aniversario
- Actualizar formulario webinar sonar y excentia

Actualización formularios

---

webinar-reducir-costes-generar-codigo-IA.html

- Añadir video resumen
- Actualizar formulario
- Otros ajustes

Actualizar página de webinar

---

evento-15-aniversario-excentia.html

Actualización agenda

---

evento-15-aniversario-excentia.html
ponencia-jira-cloud-ia-atlassian.html
ponencia-sonarcloud-enterprise-ia.html

Añadir videos resumen de Gerson y Yacine a la página de 15 aniversario
Crear landings por video

Videos resumen

---

_includes/header-en.html
_includes/header.html
_posts/2025-01-02-nueva-nomenclatura-versiones-sonarqube.md
en/3d-issues-map.html
en/atlassian.html
en/cards.html
en/debt-tracker.html
en/dependency-track-connector-jira.html
en/excentia-admin-tools.html
en/hidden-fields-for-jira.html
en/index.html
en/issue-picker-for-jira-cloud.html
en/issue-picker.html
en/nosotros.html
en/sonarqube-connector-bitbucket.html
en/sonarqube-connector-jira.html
en/time-tracking-stats.html
en/traceabilityx.html
en/workday-control.html

Actualizar descripción y eliminar acento

Correcciones

---

calidad-de-procesos.html
calidad-de-software.html

Añadir contenido en las páginas de calidad de procesos y calidad de software

Mejoras SEO

---

_posts/2025-03-14-primeros-pasos-agentes-rovo-atlassian.md
sonarqube.html

Añadir guiones a la página
Añadir video en post de Rovo

Actualizaciones
